using ClosedXML.Excel;
using Wedding.Data.Entities;

namespace Wedding.Services
{
    /// <summary>
    /// Generated by Bing 16 April 2023
    /// </summary>
    public static class ExportPartiesAndGuests
    {
        public static bool ToExcelFile(this List<Party> parties, string filename)
        {
            bool Success = false;
            //try
            //{
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Parties");
                //Write the column names
                worksheet.Cell(1, 1).Value = "PartyId";
                worksheet.Cell(1, 2).Value = "PartyName";
                worksheet.Cell(1, 3).Value = "Address";
                worksheet.Cell(1, 4).Value = "Comments";
                worksheet.Cell(1, 5).Value = "IsInvited";
                worksheet.Cell(1, 6).Value = "InvitationOpened";
                worksheet.Cell(1, 7).Value = "InvitationSent";
                worksheet.Cell(1, 8).Value = "UniqueInviteId";
                worksheet.Cell(1, 9).Value = "InviteSentDate";

                //Write the data
                for (int i = 0; i < parties.Count; i++)
                {
                    var party = parties[i];
                    worksheet.Cell(i + 2, 1).Value = party.PartyId.ToString();
                    worksheet.Cell(i + 2, 2).Value = party.PartyName;
                    worksheet.Cell(i + 2, 3).Value = party.Address;
                    worksheet.Cell(i + 2, 4).Value = party.Comments;
                    worksheet.Cell(i + 2, 5).Value = party.IsInvited;
                    worksheet.Cell(i + 2, 6).Value = party.InvitationOpened;
                    worksheet.Cell(i + 2, 7).Value = party.InvitationSent;
                    worksheet.Cell(i + 2, 8).Value = party.UniqueInviteId;
                    worksheet.Cell(i + 2, 9).Value = party.InviteSentDate;
                }

                //Save the file
                workbook.SaveAs(filename);
                Success = true;
            }
            //}
            //catch
            //{
            //    //Handle exception
            //}
            return Success;
        }

        public static bool ToExcelFile(this List<Guest> guests, string filename)
        {
            bool Success = false;
            //try
            //{
            using (var workbook = new XLWorkbook(filename))
            {
                var worksheet = workbook.Worksheets.Add("Guests");
                //Write the column names
                worksheet.Cell(1, 1).Value = "GuestId";
                worksheet.Cell(1, 2).Value = "FirstName";
                worksheet.Cell(1, 3).Value = "LastName";
                worksheet.Cell(1, 4).Value = "IsAttending";
                worksheet.Cell(1, 5).Value = "IsAttendingRehersalDinner";
                worksheet.Cell(1, 6).Value = "InviteAccepted";
                worksheet.Cell(1, 7).Value = "InvitationOpened";
                worksheet.Cell(1, 8).Value = "AgeBracket";
                worksheet.Cell(1, 9).Value = "CommonRequirements";
                worksheet.Cell(1, 10).Value = "Allergies";
                worksheet.Cell(1, 11).Value = "Other";
                worksheet.Cell(1, 12).Value = "PartyId";

                //Write the data
                for (int i = 0; i < guests.Count; i++)
                {
                    var guest = guests[i];
                    worksheet.Cell(i + 2, 1).Value = guest.GuestId.ToString();
                    worksheet.Cell(i + 2, 2).Value = guest.FirstName;
                    worksheet.Cell(i + 2, 3).Value = guest.LastName;
                    worksheet.Cell(i + 2, 4).Value = guest.IsAttending.ToString();
                    worksheet.Cell(i + 2, 5).Value = guest.IsAttendingRehersalDinner.ToString();
                    worksheet.Cell(i + 2, 6).Value = guest.InviteAccepted;
                    worksheet.Cell(i + 2, 8).Value = guest.AgeBracket.ToString();
                    worksheet.Cell(i + 2, 9).Value = string.Join(",", guest.CommonRequirements);
                    worksheet.Cell(i + 2, 10).Value = guest.Allergies;
                    worksheet.Cell(i + 2, 11).Value = guest.Other;
                    worksheet.Cell(i + 2, 12).Value = guest.PartyId.ToString();
                }

                //Save the file
                workbook.Save();
                Success = true;
            }
            //}
            //catch
            //{
            //    //Handle exception
            //}
            return Success;
        }

        public static bool ToExcelFile(this List<Party> parties, string filename, bool partyAndGuests)
        {
            bool Success = false;
            //try
            //{
            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Parties and Guests");
                //Write the column names
                worksheet.Cell(1, 1).Value = "PartyId";
                worksheet.Cell(1, 2).Value = "PartyName";
                worksheet.Cell(1, 3).Value = "Address";
                worksheet.Cell(1, 4).Value = "Comments";
                worksheet.Cell(1, 5).Value = "IsInvited";
                worksheet.Cell(1, 6).Value = "InvitationOpened";
                worksheet.Cell(1, 7).Value = "InvitationSent";
                worksheet.Cell(1, 8).Value = "UniqueInviteId";
                worksheet.Cell(1, 9).Value = "InviteSentDate";
                worksheet.Cell(1, 10).Value = "GuestId";
                worksheet.Cell(1, 11).Value = "FirstName";
                worksheet.Cell(1, 12).Value = "LastName";
                worksheet.Cell(1, 13).Value = "IsAttending";
                worksheet.Cell(1, 14).Value = "IsAttendingRehersalDinner";
                worksheet.Cell(1, 15).Value = "InviteAccepted";
                worksheet.Cell(1, 16).Value = "InvitationOpened";
                worksheet.Cell(1, 17).Value = "AgeBracket";
                worksheet.Cell(1, 18).Value = "CommonRequirements";
                worksheet.Cell(1, 19).Value = "Allergies";
                worksheet.Cell(1, 20).Value = "Other";

                //Write the data
                int rowIndex = 2;
                foreach (var party in parties)
                {
                    foreach (var guest in party.Guests)
                    {
                        //Write the party and guest data in one row
                        worksheet.Cell(rowIndex, 1).Value = party.PartyId.ToString();
                        worksheet.Cell(rowIndex, 2).Value = party.PartyName;
                        worksheet.Cell(rowIndex, 3).Value = party.Address;
                        worksheet.Cell(rowIndex, 4).Value = party.Comments;
                        worksheet.Cell(rowIndex, 5).Value = party.IsInvited;
                        worksheet.Cell(rowIndex, 6).Value = party.InvitationOpened;
                        worksheet.Cell(rowIndex, 7).Value = party.InvitationSent;
                        worksheet.Cell(rowIndex, 8).Value = party.UniqueInviteId;
                        worksheet.Cell(rowIndex, 9).Value = party.InviteSentDate;
                        worksheet.Cell(rowIndex, 10).Value = guest.GuestId.ToString();
                        worksheet.Cell(rowIndex, 11).Value = guest.FirstName;
                        worksheet.Cell(rowIndex, 12).Value = guest.LastName;
                        worksheet.Cell(rowIndex, 13).Value = guest.IsAttending.ToString();
                        worksheet.Cell(rowIndex, 14).Value = guest.IsAttendingRehersalDinner.ToString();
                        worksheet.Cell(rowIndex, 15).Value = guest.InviteAccepted;
                        worksheet.Cell(rowIndex, 17).Value = guest.AgeBracket.ToString();
                        worksheet.Cell(rowIndex, 18).Value = string.Join(",", guest.CommonRequirements);
                        worksheet.Cell(rowIndex, 19).Value = guest.Allergies;
                        worksheet.Cell(rowIndex, 20).Value = guest.Other;

                        //Increment the row index
                        rowIndex++;
                    }
                }

                //Save the file
                workbook.SaveAs(filename);
                Success = true;
            }
            //}
            //catch
            //{
            //    //Handle exception
            //}
            return Success;
        }

    }
}
