version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ash@example.com
      PGADMIN_DEFAULT_PASSWORD: password

  web:
    image: skywalkerisnull/blazor-wedding:latest
    build: 
      context: ../
      dockerfile: ./Wedding/Dockerfile
    restart: always
    ports: 
      - "5000:80"
    env_file: .env
    volumes:
      - wedding-data-qr:/app/wwwroot/qrcodes
      - wedding-data-images:/app/wwwroot/images

  storage:
    image: mcr.microsoft.com/azure-blob-storage
    restart: always
    env_file: .env
    ports:
      - 11002:11002
    volumes:
      - wedding-blob-storage:/blobroot

volumes:
  local_pgdata:
  pgadmin-data:
  wedding-data-qr:
  wedding-data-images:
  wedding-blob-storage:  