version: "3"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ash@example.com
      PGADMIN_DEFAULT_PASSWORD: password

  web:
    build: 
      context: ../
      dockerfile: ./Wedding/Dockerfile
    restart: always
    ports: 
      - "5000:80"
    env_file: .env
    volumes:
      - wedding-data/qrcodes:/app/wwwroot/qrcodes
      - wedding-data/images:/app/wwwroot/images

volumes:
  local_pgdata:
  pgadmin-data:
  wedding-data:  